from django.urls import path
from .views import (
    api_overview,
    homework_list,
    homework_detail,
    homework_create,
    homework_update,
    homework_delete,
    student_list,
    student_detail,
    student_create,
    student_update,
    student_delete,
    grade_list,
    grade_detail,
    grade_create,
    grade_update,
    grade_delete,
)

urlpatterns = [
    path('', api_overview, name="api-overview"),
    path('homeworks/', homework_list, name="homework-list"),
    path('homeworks/<str:pk>/', homework_detail, name="homework-detail"),
    path('homework-create/', homework_create, name="homework-create"),
    path('homeworks/<str:pk>/update/', homework_update, name="homework-update"),
    path('homeworks/<str:pk>/delete/', homework_delete, name="homework-delete"),
    path('students/', student_list, name="student-list"),
    path('students/<str:pk>/', student_detail, name="student-detail"),
    path('student-create/', student_create, name="student-create"),
    path('students/<str:pk>/update/', student_update, name="student-update"),
    path('students/<str:pk>/delete/', student_delete, name="student-delete"),
    path('grades/', grade_list, name="grade-list"),
    path('grades/<str:pk>/', grade_detail, name="grade-detail"),
    path('grade-create/', grade_create, name="grade-create"),
    path('grades/<str:pk>/update/', grade_update, name="grade-update"),
    path('grades/<str:pk>/delete/', grade_delete, name="grade-delete"),
]
