# Generated by Django 3.1.1 on 2020-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
